fix(ci): add version verification and print JReleaser output

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -60,12 +60,19 @@ jobs:
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           fetch-depth: 0 # Fetch all history for all branches and tags
+          ref: main # Checkout the main branch
 
-      - name: Set up JDK 21
-        uses: actions/setup-java@v4
-        with:
-          distribution: 'temurin'
-          java-version: '21'
+      - name: Verify current version
+        run: |
+          if [[ ! -f version.txt ]]; then
+            echo "version.txt file not found!"
+            exit 1
+          fi
+          current_version=$(cat version.txt)
+          if [[ ! "$current_version" =~ -SNAPSHOT$ ]]; then
+              echo "Current version is not a SNAPSHOT version: $current_version"
+              exit 1
+          fi
 
       - name: Configure Git
         run: |
@@ -77,6 +84,12 @@ jobs:
           echo "${{ github.event.inputs.releaseVersion }}" > version.txt
           git add version.txt
           git commit -a -m "chore(release): set release version to ${{ github.event.inputs.releaseVersion }}"
+
+      - name: Set up JDK 21
+        uses: actions/setup-java@v4
+        with:
+          distribution: temurin
+          java-version: 21
 
       - name: Build with Gradle
         run: ./gradlew clean publish --no-build-cache
@@ -100,3 +113,18 @@ jobs:
       - name: Push changes
         run: |
           git push origin
+
+      - name: Print JReleaser information
+        run: |
+          if [ -f build/jreleaser/output.properties ]; then
+            echo "JReleaser output properties:"
+            cat build/jreleaser/output.properties
+          else
+            echo "No JReleaser output properties found."
+          fi
+          if [ -f build/jreleaser/trace.log ]; then
+            echo "JReleaser logs:"
+            cat build/jreleaser/trace.log
+          else
+            echo "No JReleaser logs found."
+          fi
